\set ON_ERROR_STOP on
begin;
set local search_path=public,extensions;
select no_plan();
insert into auth.users(id,aud,role,email,raw_app_meta_data,raw_user_meta_data) values
 ('38200000-0000-4000-8000-000000000001','authenticated','authenticated','favorite-offer-owner@example.test','{}','{}');
insert into public.platform_operators(user_id) values('38200000-0000-4000-8000-000000000001');
insert into public.workspaces(id,name) values('38200000-0000-4000-8000-000000000011','Favorite offers');
insert into public.workspace_members(workspace_id,user_id,role) values
 ('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000001','owner');
insert into public.marketplace_connections(id,workspace_id,display_name,execution_mode,status,external_account_id) values
 ('38200000-0000-4000-8000-000000000021','38200000-0000-4000-8000-000000000011','Favorite offers','local','connected','123');
insert into public.marketplace_local_extension_grants(workspace_id,connection_id,approved_by,token_hash,external_account_id,expires_at,messages_read,messages_send) values
 ('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021','38200000-0000-4000-8000-000000000001',repeat('a',64),'123',clock_timestamp()+interval '1 hour',true,true);
insert into public.marketplace_account_entries(workspace_id,connection_id,kind,external_id,body,sort_at) values
 ('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021','publication','456','{"title":"Boots","price":40,"isClosed":false,"isReserved":false}',clock_timestamp());
create function pg_temp.config(p_offer jsonb default null) returns jsonb language sql as $$
 select '{"templates":["Danke für Dein Interesse an {article}!"],"rules":[],"delayMinutes":0,"timezone":"Europe/Berlin"}'::jsonb||jsonb_build_object('offer',p_offer);
$$;
create function pg_temp.read_settings() returns jsonb language sql as $$
 select public.marketplace_read_favorite_messages('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021');
$$;
create function pg_temp.save(p_enabled boolean,p_offer jsonb default '{"type":"amount","value":5}') returns jsonb language sql as $$
 select public.marketplace_save_favorite_messages('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',p_enabled,pg_temp.config(p_offer),coalesce((pg_temp.read_settings()->>'version')::bigint,0));
$$;
create function pg_temp.ingest(p_actor text) returns jsonb language sql as $$
 select public.marketplace_import_local_favorites('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',repeat('a',64),jsonb_build_array(jsonb_build_object('externalId',gen_random_uuid(),'actorId',p_actor,'itemId','456','eventAt',clock_timestamp()-interval '1 second')));
$$;
create function pg_temp.claim(p_supported boolean default true) returns jsonb language sql as $$
 select public.marketplace_local_favorite_claim('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',repeat('a',64),p_supported);
$$;
create function pg_temp.message_start(p_actor text) returns jsonb language sql as $$
 select public.marketplace_local_favorite_start('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',repeat('a',64),id,claim_token) from public.marketplace_favorite_message_events where actor_id=p_actor;
$$;
create function pg_temp.message_sent(p_actor text,p_message text default '888',p_conversation text default '777',p_transaction text default '666',p_token text default repeat('a',64)) returns jsonb language sql as $$
 select public.marketplace_local_favorite_message_sent('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',p_token,id,claim_token,p_message,p_conversation,p_transaction) from public.marketplace_favorite_message_events where actor_id=p_actor;
$$;
create function pg_temp.offer_start(p_actor text,p_original bigint default 4000,p_price bigint default 3500) returns jsonb language sql as $$
 select public.marketplace_local_favorite_offer_start('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',repeat('a',64),id,claim_token,p_original,p_price) from public.marketplace_favorite_message_events where actor_id=p_actor;
$$;
create function pg_temp.offer_finish(p_actor text,p_outcome text,p_external text default null,p_error text default null,p_token text default repeat('a',64)) returns jsonb language sql as $$
 select public.marketplace_local_favorite_offer_finish('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',p_token,id,claim_token,p_outcome,p_external,p_error) from public.marketplace_favorite_message_events where actor_id=p_actor;
$$;
select ok(public.marketplace_favorite_message_config_valid(pg_temp.config()-'offer'),'Old four-key config stays valid');
select ok(public.marketplace_favorite_message_config_valid(pg_temp.config()),'Explicitly disabled offer accepted');
select ok(public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":5.01}')),'Amount accepts whole cents');
select ok(public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"percentage","value":50}')),'Conservative percentage upper bound accepted');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":0}')),'Zero amount rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":-1}')),'Negative amount rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":1.001}')),'Fractions of cents rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":1000001}')),'Unbounded amount rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"percentage","value":0.5}')),'Percentage below one rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"percentage","value":51}')),'Percentage above conservative limit rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":"5"}')),'String discount rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount","value":5,"extra":true}')),'Extra offer properties rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('{"type":"amount"}')),'Missing discount value rejected');
select ok(not public.marketplace_favorite_message_config_valid(pg_temp.config('true')),'Non-object offer rejected');
select ok(not has_function_privilege('authenticated','public.marketplace_local_favorite_claim(uuid,uuid,text,boolean)','execute'),'App cannot claim offer jobs');
select ok(not has_function_privilege('anon','public.marketplace_local_favorite_message_sent(uuid,uuid,text,uuid,uuid,text,text,text)','execute'),'Anonymous callers cannot forge message checkpoint');
select ok(not has_function_privilege('authenticated','public.marketplace_local_favorite_offer_start(uuid,uuid,text,uuid,uuid,bigint,bigint)','execute'),'App cannot start offers');
select ok(not has_function_privilege('authenticated','public.marketplace_local_favorite_offer_finish(uuid,uuid,text,uuid,uuid,text,text,text)','execute'),'App cannot forge offer receipt');
select set_config('request.jwt.claim.sub','38200000-0000-4000-8000-000000000001',true);
set local role authenticated;
select lives_ok($$select pg_temp.save(true)$$,'Offer settings require explicit activation');
reset role;
update public.marketplace_favorite_message_settings set activated_at=clock_timestamp()-interval '1 minute';
set local role service_role;
select lives_ok($$select pg_temp.ingest('701')$$,'Offer favorite imported');
select is(public.marketplace_local_favorite_claim('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021',repeat('a',64))->>'command',null,'Old client cannot claim an offer setting');
select is(pg_temp.claim()->'command'->>'stage','message','New client receives the message stage first');
select throws_ok($$select pg_temp.offer_start('701')$$,'42501',null,'Offer cannot precede confirmed message');
select throws_ok($$select pg_temp.message_sent('701')$$,'42501',null,'Message receipt requires started write');
select lives_ok($$select pg_temp.message_start('701')$$,'Message starts normally');
select throws_ok($$select pg_temp.message_sent('701',null)$$,'22023',null,'Checkpoint requires provider message identifier');
select throws_ok($$select pg_temp.message_sent('701','888',null)$$,'22023',null,'Checkpoint requires provider conversation identifier');
select throws_ok($$select pg_temp.message_sent('701','888','777','666',repeat('b',64))$$,'42501',null,'Wrong token cannot checkpoint message');
select lives_ok($$select pg_temp.message_sent('701')$$,'Confirmed message creates pending offer');
select lives_ok($$select pg_temp.message_sent('701')$$,'Message checkpoint replay is idempotent');
select throws_ok($$select pg_temp.message_sent('701','889')$$,'23505',null,'Conflicting message confirmation rejected');
reset role;
select is((select state from public.marketplace_favorite_message_events where actor_id='701'),'sent','Message outcome remains sent while offer is pending');
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='701'),'pending','Offer pending persisted separately');
select is((select offer_config from public.marketplace_favorite_message_events where actor_id='701'),'{"type":"amount","value":5}'::jsonb,'Claim snapshots the intended offer');
insert into public.marketplace_account_entries(workspace_id,connection_id,kind,external_id,body,sort_at) values
 ('38200000-0000-4000-8000-000000000011','38200000-0000-4000-8000-000000000021','conversation','777','{"partnerId":"701"}',clock_timestamp());
set local role service_role;
select is(pg_temp.claim(false)->>'command',null,'Old client cannot resume pending offers');
select is(pg_temp.claim()->'command'->>'stage','offer','Restart resumes the offer despite the now existing conversation');
select is(pg_temp.claim()->>'command',null,'Occupied offer cannot be claimed twice');
select throws_ok($$select pg_temp.message_start('701')$$,'42501',null,'Offer resume never resends the message');
select throws_ok($$select pg_temp.offer_start('701',4000,3600)$$,'22023',null,'Price must match snapshotted amount');
select throws_ok($$select pg_temp.offer_start('701',900,400)$$,'22023',null,'Amount below half current price rejected');
select throws_ok($$select pg_temp.offer_start('701',500,0)$$,'22023',null,'Zero offer rejected');
select throws_ok($$select pg_temp.offer_start('701',null,3500)$$,'22023',null,'Missing current price rejected');
select lives_ok($$select pg_temp.offer_start('701')$$,'Exact amount offer starts after the message');
select throws_ok($$select pg_temp.offer_start('701')$$,'42501',null,'Offer write starts exactly once');
select throws_ok($$select pg_temp.offer_finish('701','sent')$$,'22023',null,'Offer sent requires provider confirmation');
select lives_ok($$select pg_temp.offer_finish('701','outcome_unknown',null,'timeout')$$,'Ambiguous offer persisted without changing message');
select lives_ok($$select pg_temp.offer_finish('701','outcome_unknown',null,'timeout')$$,'Ambiguous receipt replay accepted');
select is(pg_temp.claim()->>'command',null,'Unknown offer is never blindly retried');
select lives_ok($$select pg_temp.offer_finish('701','sent','999')$$,'Provider receipt can settle same unknown attempt');
select lives_ok($$select pg_temp.offer_finish('701','sent','999')$$,'Confirmed offer replay accepted');
select throws_ok($$select pg_temp.offer_finish('701','sent','998')$$,'23505',null,'Conflicting offer receipt rejected');
reset role;
select is((select offer_price_cents from public.marketplace_favorite_message_events where actor_id='701'),3500::bigint,'Chosen cents survive completion');
set local role authenticated;
select is(pg_temp.read_settings()->'events'->0->>'state','sent','History exposes the successful message outcome');
select is(pg_temp.read_settings()->'events'->0->>'offerState','sent','History exposes the independent offer outcome');
select is(pg_temp.read_settings()->'events'->0->>'offerPriceCents','3500','History includes chosen price');
reset role;
set local role service_role;
select lives_ok($$select pg_temp.ingest('702')$$,'Independent missing-transaction fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','702','Independent message claimed');
select lives_ok($$select pg_temp.message_start('702')$$,'Missing-transaction message starts');
select lives_ok($$select pg_temp.message_sent('702','888','778',null)$$,'Message confirmed without a transaction');
select throws_ok($$select pg_temp.offer_start('702')$$,'42501',null,'Missing transaction forbids offer');
reset role;
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='702'),'skipped','Missing transaction skips the offer only');
select is((select offer_error_code from public.marketplace_favorite_message_events where actor_id='702'),'missing_transaction','Missing transaction reason retained');
set local role service_role;
select lives_ok($$select pg_temp.ingest('703')$$,'Offer lease fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','703','Offer lease message claimed');
select lives_ok($$select pg_temp.message_start('703')$$,'Lease message started');
select lives_ok($$select pg_temp.message_sent('703')$$,'Lease message confirmed');
select is(pg_temp.claim()->'command'->>'stage','offer','Unstarted offer claimed');
reset role;
update public.marketplace_favorite_message_events set lease_expires_at=clock_timestamp()-interval '1 second' where actor_id='703';
set local role service_role;
select is(pg_temp.claim()->'command'->>'actorId','703','Expired unstarted offer can be recovered');
select lives_ok($$select pg_temp.offer_start('703')$$,'Recovered offer starts');
reset role;
update public.marketplace_favorite_message_events set lease_expires_at=clock_timestamp()-interval '1 second' where actor_id='703';
set local role service_role;
select is(pg_temp.claim()->>'command',null,'Expired started offer is not reclaimed');
reset role;
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='703'),'outcome_unknown','Expired started offer becomes unknown');
select is((select state from public.marketplace_favorite_message_events where actor_id='703'),'sent','Offer timeout preserves message confirmation');
set local role authenticated;
select lives_ok($$select pg_temp.save(true,'{"type":"percentage","value":10}')$$,'Percentage config saved explicitly');
reset role;
set local role service_role;
select lives_ok($$select pg_temp.ingest('704')$$,'Rounding fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','704','Percentage message claimed');
select lives_ok($$select pg_temp.message_start('704')$$,'Percentage message started');
select lives_ok($$select pg_temp.message_sent('704')$$,'Percentage message confirmed');
select throws_ok($$select pg_temp.offer_start('704',1005,904)$$,'22023',null,'Percentage must round to nearest whole cent');
select lives_ok($$select pg_temp.offer_start('704',1005,905)$$,'Percentage rounds half a cent upward');
select lives_ok($$select pg_temp.offer_finish('704','failed',null,'provider_rejected')$$,'Confirmed offer failure retained');
select is(pg_temp.claim()->>'command',null,'Confirmed failure is never retried automatically');
select lives_ok($$select pg_temp.ingest('705')$$,'Configuration-change fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','705','Configuration-change message claimed');
select lives_ok($$select pg_temp.message_start('705')$$,'Configuration-change message started');
select lives_ok($$select pg_temp.message_sent('705')$$,'Configuration-change message confirmed');
select is(pg_temp.claim()->'command'->>'stage','offer','Configuration-change offer claimed');
reset role;
set local role authenticated;
select lives_ok($$select pg_temp.save(false)$$,'Disabling cancels pending offer');
reset role;
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='705'),'skipped','Disabling skips already claimed offer');
select is((select offer_error_code from public.marketplace_favorite_message_events where actor_id='705'),'configuration_changed','Cancellation reason persisted separately');
select is((select state from public.marketplace_favorite_message_events where actor_id='705'),'sent','Disabling does not erase confirmed message');
set local role service_role;
select throws_ok($$select pg_temp.offer_start('705')$$,'42501',null,'Disabled offer cannot start');
select lives_ok($$select pg_temp.offer_finish('705','skipped',null,'inactive_item')$$,'Late pre-write skip acknowledges configuration cancellation');
select lives_ok($$select pg_temp.offer_finish('705','failed',null,'provider_unavailable')$$,'Late read failure acknowledges configuration cancellation');
select throws_ok($$select pg_temp.offer_finish('705','outcome_unknown',null,'timeout')$$,'23505',null,'Unknown write cannot override unstarted configuration cancellation');
select throws_ok($$select pg_temp.offer_finish('705','sent','999')$$,'23505',null,'Receipt cannot invent an unstarted cancelled offer');
reset role;
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='705'),'skipped','Late pre-write result preserves server cancellation');
select is((select offer_error_code from public.marketplace_favorite_message_events where actor_id='705'),'configuration_changed','Late pre-write result preserves authoritative cancellation reason');
set local role authenticated;
select lives_ok($$select pg_temp.save(true)$$,'Explicit reactivation');
reset role;
update public.marketplace_favorite_message_settings set activated_at=clock_timestamp()-interval '1 minute';
set local role service_role;
select lives_ok($$select pg_temp.ingest('706')$$,'Late receipt fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','706','Late receipt message claimed');
select lives_ok($$select pg_temp.message_start('706')$$,'Late receipt message started');
reset role;
set local role authenticated;
select lives_ok($$select pg_temp.save(true)$$,'Version changes while message is writing');
reset role;
set local role service_role;
select lives_ok($$select pg_temp.message_sent('706')$$,'Confirmed late message still recorded');
reset role;
select is((select offer_state from public.marketplace_favorite_message_events where actor_id='706'),'skipped','Late receipt cannot revive an old-version offer');
select is((select offer_error_code from public.marketplace_favorite_message_events where actor_id='706'),'configuration_changed','Late receipt carries configuration-change reason');
set local role service_role;
select lives_ok($$select pg_temp.ingest('707')$$,'Revocation fixture imported');
select is(pg_temp.claim()->'command'->>'actorId','707','Revocation message claimed');
select lives_ok($$select pg_temp.message_start('707')$$,'Revocation message started');
select lives_ok($$select pg_temp.message_sent('707')$$,'Revocation message confirmed');
reset role;
update public.marketplace_connections set external_account_id='124';
set local role service_role;
select throws_ok($$select pg_temp.offer_start('707')$$,'42501',null,'Changed account cannot send an offer');
reset role;
update public.marketplace_connections set external_account_id='123';
update public.marketplace_local_extension_grants set messages_send=false;
set local role service_role;
select throws_ok($$select pg_temp.offer_start('707')$$,'42501',null,'Missing send authorization cannot start offer');
reset role;
update public.marketplace_local_extension_grants set messages_send=true,grant_generation=grant_generation+1;
set local role service_role;
select throws_ok($$select pg_temp.offer_start('707')$$,'42501',null,'Replacement grant cannot inherit pending offer');
reset role;
update public.marketplace_local_extension_grants set grant_generation=grant_generation-1;
set local role service_role;
select lives_ok($$select pg_temp.offer_start('707')$$,'Unchanged active grant can start');
reset role;
update public.marketplace_local_extension_grants set revoked_at=clock_timestamp();
set local role service_role;
select throws_ok($$select pg_temp.claim()$$,'42501',null,'Revocation stops further claims');
select throws_ok($$select pg_temp.offer_start('707')$$,'42501',null,'Revoked grant cannot restart');
select throws_ok($$select pg_temp.offer_finish('707','sent','999',null,repeat('b',64))$$,'42501',null,'Wrong receipt credentials rejected after revocation');
select lives_ok($$select pg_temp.offer_finish('707','sent','999')$$,'Revocation still permits receipt for already started write');
select lives_ok($$select pg_temp.offer_finish('707','sent','999')$$,'Same confirmed receipt replays after revocation');
select * from finish();
rollback;
