begin;
select label_test.assert_true((select count(*) = 2 and bool_and(not public) from storage.buckets),'Referenzbilder sind privat');
set local role anon;
select label_test.expect_error('select public.list_size_references(false)','42501','Keine anonymen Größenreferenzen');
select label_test.expect_error('select public.list_label_admin_images()','42501','Keine anonyme Bildverwaltung');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000002',true);
set local role authenticated;
select label_test.expect_error('select public.list_size_references(true)','42501','Kunden sehen keine Größenentwürfe');
select label_test.expect_error('select public.reserve_label_image(gen_random_uuid(),null)','42501','Kunden reservieren keine Bilder');
select label_test.expect_error('select public.complete_label_image(1,gen_random_uuid(),1,''image/png'',1,1,''a'',''b'')','42501','Browser darf Upload nicht selbst freigeben');
reset role;
select set_config('request.jwt.claim.sub','00000000-0000-0000-0000-000000000001',true);
set local role authenticated;
do $$
declare content jsonb := '{"title":"Hosen Test","category":"trousers","audience":"unisex","measurement":"body","notes":"W/L nach Hersteller","sourceTitle":"Hersteller","sourceUrl":"https://example.com/sizes","reviewedAt":"2026-01-01","columns":["W","Bund cm"],"rows":[["32","81"]]}';
 saved jsonb; request_id uuid := gen_random_uuid(); id integer; upload jsonb; upload_input jsonb;
begin
 saved := public.save_size_reference(null,null,null,content,true,request_id);id := (saved->>'id')::integer;
 perform label_test.assert_true(public.save_size_reference(null,null,null,content,true,request_id)=saved,'Größenauftrag wird genau einmal ausgeführt');
 perform label_test.expect_error(format('select public.save_size_reference(null,null,null,%L,true,%L)',content||'{"title":"Anders"}',request_id),'22023','Vorgangskennung bindet den Inhalt');
 perform label_test.expect_error(format('select public.save_size_reference(%s,2,null,%L,false,gen_random_uuid())',id,content),'P0001','Versionskonflikt überschreibt keine Größe');
 perform public.save_size_reference(id,1,null,content||'{"title":"Neue Fassung"}',false,gen_random_uuid());
 perform label_test.assert_true(public.list_size_references(false)->0->'content'->>'title'='Hosen Test','Entwurf ändert keine veröffentlichte Größe');
 perform label_test.assert_true(public.list_size_references(true)->0->>'hasDraftChanges'='true','Redaktion erkennt unveröffentlichte Änderung');
 perform label_test.expect_error(format('select public.save_size_reference(null,null,null,%L,true,gen_random_uuid())',content||'{"rows":[["32"]]}'),'22023','Uneinheitliche Tabellen werden abgewiesen');
 perform label_test.expect_error(format('select public.save_size_reference(null,null,null,%L,true,gen_random_uuid())',content||'{"sourceUrl":""}'),'22023','Veröffentlichen erfordert Quelle');
 perform public.archive_size_reference(id,2,true,gen_random_uuid());
 perform label_test.assert_true(public.list_size_references(false)='[]','Archivierte Größen sind verborgen');
 perform public.archive_size_reference(id,3,false,gen_random_uuid());
 perform label_test.assert_true(jsonb_array_length(public.list_size_references(false))=1,'Wiederherstellung erhält veröffentlichte Größe');
 perform label_test.expect_error(format('update public.size_references set archived=true where id=%s',id),'42501','Keine direkten Browser-Schreibrechte');
 request_id := gen_random_uuid();
 upload_input := jsonb_build_object('originalHash',repeat('a',64),'imageHash',repeat('b',64),'attribution','Eigenes Foto','allowedUse','Referenzbibliothek');
 upload := public.reserve_label_image(request_id,upload_input);
 perform label_test.assert_true(public.reserve_label_image(request_id,upload_input)=upload,'Uploadreservierung ist wiederholbar');
 perform label_test.expect_error(format('select public.reserve_label_image(%L,%L)',request_id,upload_input||jsonb_build_object('imageHash',repeat('c',64))),'22023','Uploadauftrag bindet Bildinhalt');
 perform label_test.assert_true(not public.can_read_label_image((upload->>'assetId')||'.png'),'Unverarbeitete Bilder werden nicht ausgeliefert');
 perform label_test.assert_true(public.set_label_library_enabled(true,gen_random_uuid())->>'readerEnabled'='true','Leserfreigabe bestätigt exakt den Auftrag');
end;
$$;
reset role;
rollback;
